"""fix date

Revision ID: 6d8b589d967b
Revises: 
Create Date: 2021-11-30 14:32:06.765191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8b589d967b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('blog', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('data', sa.DATETIME(), nullable=True))
    op.drop_column('blog', 'date')
    # ### end Alembic commands ###
